### PR TITLE
Integrate with a new version of broccoli-scss-linter

### PR DESCRIPTION
**Pull request by artursmirnov**
I have completely rewritten the `broccoli-scss-linter` in order to improve its performance. Now it runs ~10 times faster for me comparing to previous version.

* I have dropped all unnecessary stuff like formatters, etc. and simplified the code a lot.
* Now it runs against all tree at once instead of running agains each single file.
* Also now it uses new broccoli syntax which requires some changes in the ember addon
* Console output is a bit fine-tuned
* Now it breaks the build in case of error (a rule with `severity: error`)

### CODE REVIEW

**Comment by tomasbasham** [comment]
Fantastic. I'm really glad you have found the time to improve the scss linting package. I agree it was incredibly slow (almost painful) in large applications. I'll merge this in when I can

**Comment by tomasbasham** [comment]
I can sort out the tests too. I need to re-write them anyway because they were a bit of a rush job

**Comment by artursmirnov** [comment]
Thanks! 

If you feel you need anything else related to the broccoli plugin, please don't hesitate to ask me.

**Comment by tomasbasham** [comment]
I've just got around to merging this in. I am currently testing it on a large application I am involved with and I have deliberately included errors into my scss files. However I don't get any errors on my console. Is there any setup I need to do.

**Comment by tomasbasham** [comment]
@artursmirnov Ok so I basically put a console.log into your code locally to determine what was output from the `buildCommand` function. An example of what was out put is:

`scss-lint /Users/tbm/Projects/Programming/Projects/JavaScript/whichledlight/tmp/scss_linter-input_base_path-lX50hyDb.tmp/0 --config /Users/tbm/Projects/Programming/Projects/JavaScript/whichledlight/.scss-lint.yml`

This gave no output despite there being deliberate errors in my SCSS code. I tried the following and it successfully spat our errors

`scss-lint /Users/tbm/Projects/Programming/Projects/JavaScript/whichledlight/tmp/scss_linter-input_base_path-lX50hyDb.tmp/0/ --config /Users/tbm/Projects/Prograing/Projects/JavaScript/whichledlight/.scss-lint.yml`

Notice the extra slash on the end of the input path. Seems it is necessary. Have you noticed similar things whilst testing your plugin?

**Comment by artursmirnov** [comment]
Nice catch! I'm using this new version with ember-cli-scss-lint for several days, since the PR was submitted. And it works just fine for me. But I'm using Windows and it has very different symlinks implementation, so thanks for your investigation on Unix. I will test your PR tomorrow morning and merge if it works on Windows.

**Comment by artursmirnov** [comment]
I have merged your [fix](https://github.com/artursmirnov/broccoli-scss-lint/pull/1) for broccoli plugin and updated this PR with patched version. Could you please take a look again?

**Comment by tomasbasham** [comment]
Perfect

**Pull request merged**
